// Skeleton class generated by rmic, do not edit.
// Contents subject to change without notice.

package de.fhl.haoze.concertbookingcallback;

public final class ConcertClient_Skel
    implements java.rmi.server.Skeleton
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("boolean printBookingInfo(java.util.List)")
    };
    
    private static final long interfaceHash = -6924533556128443058L;
    
    public java.rmi.server.Operation[] getOperations() {
	return (java.rmi.server.Operation[]) operations.clone();
    }
    
    public void dispatch(java.rmi.Remote obj, java.rmi.server.RemoteCall call, int opnum, long hash)
	throws java.lang.Exception
    {
	if (opnum < 0) {
	    if (hash == -776595166109715767L) {
		opnum = 0;
	    } else {
		throw new java.rmi.UnmarshalException("invalid method hash");
	    }
	} else {
	    if (hash != interfaceHash)
		throw new java.rmi.server.SkeletonMismatchException("interface hash mismatch");
	}
	
	de.fhl.haoze.concertbookingcallback.ConcertClient server = (de.fhl.haoze.concertbookingcallback.ConcertClient) obj;
	switch (opnum) {
	case 0: // printBookingInfo(List)
	{
	    java.util.List $param_List_1;
	    try {
		java.io.ObjectInput in = call.getInputStream();
		$param_List_1 = (java.util.List) in.readObject();
	    } catch (java.io.IOException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } catch (java.lang.ClassNotFoundException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } finally {
		call.releaseInputStream();
	    }
	    boolean $result = server.printBookingInfo($param_List_1);
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeBoolean($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	default:
	    throw new java.rmi.UnmarshalException("invalid method number");
	}
    }
}
